os: linux
dist: jammy

language: c

jobs:
    include:
        - name: "linux-s390x-gcc"
          os: linux
          arch: s390x
          compiler: gcc
          env: CONFIG_OPTS="--enable-fips --enable-internal-tests"
        - name: "linux-s390x-clang"
          os: linux
          arch: s390x
          compiler: clang
          env: CONFIG_OPTS="--enable-fips --enable-internal-tests"
        - name: "linux-s390x-sanitizer"
          os: linux
          arch: s390x
          compiler: gcc
          env: CONFIG_OPTS="--enable-fips --enable-internal-tests --enable-sanitizer"

before_script:
    - ./bootstrap.sh 2> >(tee)

script:
    - ./configure $CONFIG_OPTS 2> >(tee) && make check V=0 2> >(tee)
